baseURL = 'http://projektkateryna.org/'
languageCode = 'en-us'
title = 'Projekt Kateryna'
theme = 'hugo-xmag'
buildDrafts = false
paginate = 100

[permalinks]
  post = '/:filename/'
  categories = "/k/:title/"

[params]
  description = "Projekt Kateryna : The decolonisation of Ukrainian history on Wikipedia."
  images = ['/Logo-Projekt_Kateryna.png']
  footer = "&copy; Projekt Kateryna 2023" 
  summary_length = 250
  favicon = ""

[menu]

  [[menu.main]]
  name = 'Blog posts'
  url = '/'
  identifier = 'posts'
  weight = 10

    [[menu.main]]
    name = 'Purpose'
    url = '/about/#1-purpose'
    identifier = 'purpose'
    parent = 'About'
    weight = 10

    [[menu.main]]
    name = 'Problem Definition'
    url = '/about/#2-problem-definition'
    identifier = 'problem'
    parent = 'About'
    weight = 20

    [[menu.main]]
    name = 'The opportunity'
    url = '/about/#3-the-opportunity'
    identifier = 'opportunity'
    parent = 'About'
    weight = 30

    [[menu.main]]
    name = 'Content'
    url = '/about/#4-content'
    identifier = 'content'
    parent = 'About'
    weight = 40

    [[menu.main]]
    name = 'A role model: Projekt Fredrika'
    url = '/about/#5-a-role-model-projekt-fredrika'
    identifier = 'rolemodel'
    parent = 'About'
    weight = 50

    [[menu.main]]
    name = 'The team'
    url = '/about/#6-the-team'
    identifier = 'team'
    parent = 'About'
    weight = 60